default_platform(:ios)

platform :ios do
  lane :release_firebase do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:316769946877:ios:180b0a35dc0604e8b50294",
      service_credentials_file: "fastlane/service-account.json"
    )

    commit = last_git_commit

    increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })

    build_app(
      workspace: "uoslife.xcworkspace",
      scheme: "UOSLIFE-Alpha",
      export_method: "ad-hoc"
    )

    firebase_app_distribution(
      app: "1:316769946877:ios:180b0a35dc0604e8b50294",
      googleservice_info_plist_path: "ios/Resources/Alpha/GoogleService-Info.plist",
      groups: "uoslife",
      release_notes: commit[:message],
    )

    slack(
      slack_url: "https://hooks.slack.com/services/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",
      icon_url: "https://cdn.uoslife.net/logo/NewAppIconColored.png",
      username: "[Fastlane] UOSLIFE Alpha",
      message: ":white_check_mark: Firebase 빌드가 업로드되었어요 (" + commit[:message] + ")",
      success: true,
      payload: {
        "Build Number" => latest_release[:buildVersion].to_i + 1,
        "Build Time" => Time.new.to_s,
        "Commit Message" => commit[:message],
      },
      default_payloads: [:git_branch, :git_author]
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :release_testflight do
    increment_build_number(xcodeproj: "uoslife.xcodeproj")
    build_app(
      workspace: "uoslife.xcworkspace",
      scheme: "UOSLIFE-Prod"
    )
    upload_to_testflight(app_version: ENV['APP_LATEST_VERSION'])

    commit = last_git_commit
    
    slack(
      slack_url: "https://hooks.slack.com/services/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",
      icon_url: "https://cdn.uoslife.net/logo/NewAppIconColored.png",
      username: "[Fastlane] UOSLIFE Prod",
      message: ":white_check_mark: iOS: testflight 빌드가 업로드되었어요 (" + commit[:message] + ")",
      success: true,
      payload: {
        "Build Number" => get_build_number(xcodeproj: "uoslife.xcodeproj"),
        "App Version" => ENV['APP_LATEST_VERSION'],
        "Build Time" => Time.new.to_s,
        "Commit Message" => commit[:message],
      },
      default_payloads: [:git_branch, :git_author]
    )
  end
end
